
package com.actimize.eventhandlerservice.wsdl;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CMSPortType8082", targetNamespace = "http://efe-7papps001.dev.mtb.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMSPortType8082 {


    /**
     * 
     * @param sendCMSRequest
     */
    @WebMethod
    @Oneway
    public void sendCMS(
        @WebParam(name = "sendCMSRequest", targetNamespace = "http://efe-7papps001.dev.mtb.com", partName = "sendCMSRequest")
        SendCMSRequestType sendCMSRequest);

}
