
package com.actimize.eventhandlerservice.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CMSService8082", targetNamespace = "http://efe-7papps001.dev.mtb.com", wsdlLocation = "file:/C:/Users/Diwakar/eclipse-workspace/FCD/src/main/resources/wsdl/fcdtemp.wsdl")
public class CMSService8082
    extends Service
{

    private final static URL CMSSERVICE8082_WSDL_LOCATION;
    private final static WebServiceException CMSSERVICE8082_EXCEPTION;
    private final static QName CMSSERVICE8082_QNAME = new QName("http://efe-7papps001.dev.mtb.com", "CMSService8082");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Diwakar/eclipse-workspace/FCD/src/main/resources/wsdl/fcdtemp.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMSSERVICE8082_WSDL_LOCATION = url;
        CMSSERVICE8082_EXCEPTION = e;
    }

    public CMSService8082() {
        super(__getWsdlLocation(), CMSSERVICE8082_QNAME);
    }

    public CMSService8082(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMSSERVICE8082_QNAME, features);
    }

    public CMSService8082(URL wsdlLocation) {
        super(wsdlLocation, CMSSERVICE8082_QNAME);
    }

    public CMSService8082(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMSSERVICE8082_QNAME, features);
    }

    public CMSService8082(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMSService8082(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CMSPortType8082
     */
    @WebEndpoint(name = "CMSPort8082")
    public CMSPortType8082 getCMSPort8082() {
        return super.getPort(new QName("http://efe-7papps001.dev.mtb.com", "CMSPort8082"), CMSPortType8082.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMSPortType8082
     */
    @WebEndpoint(name = "CMSPort8082")
    public CMSPortType8082 getCMSPort8082(WebServiceFeature... features) {
        return super.getPort(new QName("http://efe-7papps001.dev.mtb.com", "CMSPort8082"), CMSPortType8082.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMSSERVICE8082_EXCEPTION!= null) {
            throw CMSSERVICE8082_EXCEPTION;
        }
        return CMSSERVICE8082_WSDL_LOCATION;
    }

}
